name: sound_effect_2
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  file_picker: ^11.0.2
  just_audio: ^0.10.6
  archive: ^4.0.9
  path_provider: ^2.1.6
  google_fonts: ^8.1.0
  provider: ^6.1.5+1
  ffmpeg_kit_flutter_new: ^4.3.2
  ffi: ^2.1.4
  google_mobile_ads: ^9.0.0
  colorize: ^3.0.0
  flutter_localizations:
    sdk: flutter
  intl: any
  permission_handler: ^11.3.1
  device_info_plus: ^11.1.0
  path: ^1.9.0
  media_store_plus: ^0.1.3
  external_path: ^3.0.0
  flutter_screenutil: ^5.9.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "ic_launcher"
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
